/** Generated by YAKINDU Statechart Tools code generator. */
package fr.univcotedazur.polytech.si4.fsm.project.defaultsm;

import fr.univcotedazur.polytech.si4.fsm.project.IStatemachine;
import fr.univcotedazur.polytech.si4.fsm.project.ITimerCallback;
import java.util.List;

public interface IDefaultSMStatemachine extends ITimerCallback,IStatemachine {
	public interface SCInterface {
	
		public void raiseCoinSlot(long value);
		
		public void raiseNFC(long value);
		
		public void raiseSelectType(String value);
		
		public void raiseSugarSlider(long value);
		
		public void raiseSizeSlider(long value);
		
		public void raiseTemperatureSlider(long value);
		
		public void raiseCancelButton();
		
		public void raiseGoNextStep();
		
		public void raiseDrinkCollected();
		
		public boolean isRaisedDoUpdateAmountMoney();
		
		public long getDoUpdateAmountMoneyValue();
		
		public boolean isRaisedDoTypeSelection();
		
		public String getDoTypeSelectionValue();
		
		public boolean isRaisedDoSaveInformations();
		
		public long getDoSaveInformationsValue();
		
		public boolean isRaisedDoReset();
		
		public boolean isRaisedDoRefoundMoney();
		
		public boolean isRaisedDoStartingPreparation();
		
		public boolean isRaisedDoCleanSystem();
		
		public boolean isRaisedDoInitialisation();
		
		public boolean isRaisedDoSetTemperatureAndCup();
		
		public boolean isRaisedDoPutSugarAndWater();
		
		public boolean isRaisedDoBrewing();
		
		public boolean isRaisedDoRemoveTeaBag();
		
		public boolean isRaisedDoDrinkCollectable();
		
		public long getBalance();
		
		public void setBalance(long value);
		
		public long getPrice();
		
		public void setPrice(long value);
		
		public String getType();
		
		public void setType(String value);
		
	public List<SCInterfaceListener> getListeners();
	}
	
	public interface SCInterfaceListener {
	
		public void onDoUpdateAmountMoneyRaised(long value);
		public void onDoTypeSelectionRaised(String value);
		public void onDoSaveInformationsRaised(long value);
		public void onDoResetRaised();
		public void onDoRefoundMoneyRaised();
		public void onDoStartingPreparationRaised();
		public void onDoCleanSystemRaised();
		public void onDoInitialisationRaised();
		public void onDoSetTemperatureAndCupRaised();
		public void onDoPutSugarAndWaterRaised();
		public void onDoBrewingRaised();
		public void onDoRemoveTeaBagRaised();
		public void onDoDrinkCollectableRaised();
		}
	
	public SCInterface getSCInterface();
	
}
