/** Generated by YAKINDU Statechart Tools code generator. */
package fr.univcotedazur.polytech.si4.fsm.project.defaultsm;

import fr.univcotedazur.polytech.si4.fsm.project.IStatemachine;
import fr.univcotedazur.polytech.si4.fsm.project.ITimerCallback;
import java.util.List;

public interface IDefaultSMStatemachine extends ITimerCallback,IStatemachine {
	public interface SCInterface {
	
		public void raiseSelectType(String value);
		
		public void raiseCoinSlot(long value);
		
		public void raiseNFC(long value);
		
		public void raiseSugarSlider(long value);
		
		public void raiseSizeSlider(long value);
		
		public void raiseTemperatureSlider(long value);
		
		public void raiseCancelButton();
		
		public void raiseGoNextStep();
		
		public void raiseDrinkCollected();
		
		public boolean isRaisedDoTypeSelection();
		
		public String getDoTypeSelectionValue();
		
		public boolean isRaisedDoUpdateAmountMoney();
		
		public long getDoUpdateAmountMoneyValue();
		
		public boolean isRaisedDoSaveInformations();
		
		public long getDoSaveInformationsValue();
		
		public boolean isRaisedDoReset();
		
		public boolean isRaisedDoShowOptions();
		
		public String getDoShowOptionsValue();
		
		public boolean isRaisedDoAddSplashOfMilk();
		
		public boolean isRaisedDoAddMapleSyrup();
		
		public boolean isRaisedDoAddMixedIceCream();
		
		public boolean isRaisedDoAddCroutons();
		
		public boolean isRaisedDoPress();
		
		public boolean isRaisedDoRefoundMoney();
		
		public boolean isRaisedDoStartingPreparation();
		
		public boolean isRaisedDoHeatingWater();
		
		public boolean isRaisedDoPutProduct();
		
		public String getDoPutProductValue();
		
		public boolean isRaisedDoSetTemperature();
		
		public boolean isRaisedDoSetCup();
		
		public boolean isRaisedDoPutSugar();
		
		public boolean isRaisedDoPourWater();
		
		public boolean isRaisedDoBrewing();
		
		public boolean isRaisedDoRemoveTeaBag();
		
		public boolean isRaisedDoDrinkCollectable();
		
		public boolean isRaisedDoCleanSystem();
		
		public long getBalance();
		
		public void setBalance(long value);
		
		public long getPrice();
		
		public void setPrice(long value);
		
		public String getType();
		
		public void setType(String value);
		
	public List<SCInterfaceListener> getListeners();
	}
	
	public interface SCInterfaceListener {
	
		public void onDoTypeSelectionRaised(String value);
		public void onDoUpdateAmountMoneyRaised(long value);
		public void onDoSaveInformationsRaised(long value);
		public void onDoResetRaised();
		public void onDoShowOptionsRaised(String value);
		public void onDoAddSplashOfMilkRaised();
		public void onDoAddMapleSyrupRaised();
		public void onDoAddMixedIceCreamRaised();
		public void onDoAddCroutonsRaised();
		public void onDoPressRaised();
		public void onDoRefoundMoneyRaised();
		public void onDoStartingPreparationRaised();
		public void onDoHeatingWaterRaised();
		public void onDoPutProductRaised(String value);
		public void onDoSetTemperatureRaised();
		public void onDoSetCupRaised();
		public void onDoPutSugarRaised();
		public void onDoPourWaterRaised();
		public void onDoBrewingRaised();
		public void onDoRemoveTeaBagRaised();
		public void onDoDrinkCollectableRaised();
		public void onDoCleanSystemRaised();
		}
	
	public SCInterface getSCInterface();
	
}
